# Generated by Django 5.2.3 on 2025-06-27 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='createdAt',
            new_name='created_at',
        ),
    ]
