# Generated by Django 5.2.3 on 2025-07-01 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_createdat_tasks_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='title',
            field=models.CharField(default='title', max_length=200),
        ),
    ]
